@api = http://localhost:3000

POST {{api}}/
Content-Type: application/json

{
  "username": "hector",
  "phone_number": "6462705566",
  "email": "al21760277@ite.edu.mx",
  "password_u": "password",
  "creation_date": "2025-05-08T10:00:00Z"
}

###
POST {{api}}/login
Content-Type: application/json

{
    "email": "al21760277@ite.edu.mx",
    "password": "password"
}

###
POST {{api}}/assign
Content-Type: application/json
Authorization: Bearer jwt

{
  "userId": "0c0e6b9a-4b19-4589-a07a-279c0ef64b05",
  "deviceName": "chuche test",    
  "macAddress": "d8:f3:bc:5b:22:95",  
  "channel": 1    
}