@api = http://localhost:3000

POST {{api}}/
Content-Type: application/json

{
  "username": "hector",
  "phone_number": "6462705566",
  "email": "al21760277@ite.edu.mx",
  "password_u": "password"
}

###
POST {{api}}/login
Content-Type: application/json

{
    "email": "al21760277@ite.edu.mx",
    "password": "password"
}

###
POST {{api}}/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3ODhjYWMzLTMyYzUtNDdkNC05MmUyLTdkZDRhZDNjNzI5MCIsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJhbDIxNzYwMjc3QGl0ZS5lZHUubXgiLCJpYXQiOjE3NDY3NDUxMTV9.8RtHwwI0Px2KY-8ItqOxCkJZFuDDCE0D-Q1FU6WhBg0

{
  "userId": "d788cac3-32c5-47d4-92e2-7dd4ad3c7290",
  "deviceName": "chuche test",    
  "macAddress": "v1:21:YY:8t:22:01",  
  "channel": 1,
  "longitude": -116.606,
  "latitude": 31.8153   
}

###
PATCH {{api}}/9cff0222-3243-4176-bb62-554f161eb113/lost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3ODhjYWMzLTMyYzUtNDdkNC05MmUyLTdkZDRhZDNjNzI5MCIsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJhbDIxNzYwMjc3QGl0ZS5lZHUubXgiLCJpYXQiOjE3NDY3NDUxMTV9.8RtHwwI0Px2KY-8ItqOxCkJZFuDDCE0D-Q1FU6WhBg0

{
  "deviceId": "9cff0222-3243-4176-bb62-554f161eb113"
}