@api = http://localhost:3000

POST {{api}}/
Content-Type: application/json

{
  "username": "hector",
  "phone_number": "6462705566",
  "email": "al21760277@ite.edu.mx",
  "password_u": "password"
}

###
POST {{api}}/login
Content-Type: application/json

{
    "email": "al21760277@ite.edu.mx",
    "password": "password"
}

###
POST {{api}}/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2ZGM1MGFiLTIxY2EtNGY4Mi1hOTQ2LTMxODYxNWM0Y2I0NyIsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJhbDIxNzYwMjc3QGl0ZS5lZHUubXgiLCJpYXQiOjE3NDY3NDcxNjJ9.6aqXJL5U1zBWp20nL2uegpYWIFC7uyeMpVkEIGB5thE

{
  "userId": "c6dc50ab-21ca-4f82-a946-318615c4cb47",
  "deviceName": "uno mas",    
  "macAddress": "A1:31:YY:8t:22:01",  
  "channel": 1,
  "longitude": -116.606,
  "latitude": 31.8153   
}

###
PATCH {{api}}/58594193-6d75-407e-b257-af4ecc6ff792/lost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2ZGM1MGFiLTIxY2EtNGY4Mi1hOTQ2LTMxODYxNWM0Y2I0NyIsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJhbDIxNzYwMjc3QGl0ZS5lZHUubXgiLCJpYXQiOjE3NDY3NDcxNjJ9.6aqXJL5U1zBWp20nL2uegpYWIFC7uyeMpVkEIGB5thE

{
  "deviceId": "58594193-6d75-407e-b257-af4ecc6ff792"
}

###
GET  {{api}}/user/c6dc50ab-21ca-4f82-a946-318615c4cb47
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2ZGM1MGFiLTIxY2EtNGY4Mi1hOTQ2LTMxODYxNWM0Y2I0NyIsInVzZXJuYW1lIjoiaGVjdG9yIiwiZW1haWwiOiJhbDIxNzYwMjc3QGl0ZS5lZHUubXgiLCJpYXQiOjE3NDY3NDcxNjJ9.6aqXJL5U1zBWp20nL2uegpYWIFC7uyeMpVkEIGB5thE

{
  "userId": "c6dc50ab-21ca-4f82-a946-318615c4cb47"
}